### ISSUE TITLE
Sorry, you are not allowed to access this page.

### ISSUE THREAD

**Issue by djsteven** [shailancom/dropdown-menu-widget#1]
This appear right after installing
WP 4.9

**Comment by clerik** [comment]
I have the same issue when I try to access the settings page. This is new with version 1.9.5 (maybe earlier).

I migrated a WordPress 3.x last autumn and everything was working fine at this time. Now I can't access the page and the UI is broken.

Any idea why this could happen ?

I tried different version, uninstall, reinstall, nothing.

**Comment by nnsense** [comment]
Same here

**Comment by metinsaylan** [comment]
Version 1.9.7 should solve this issue.
