### ISSUE TITLE
How to change the front color of the menu items that is not clicked on

### ISSUE THREAD

**Issue by ProTools007** [shailancom/dropdown-menu-widget#3]
I have installed this plugin to make a nice navigation dropdown menu in the header.

It seems that it also have influenced positively on the layout of my site bar. But I want to change a color in it.

The background color of my site bar is black. And when I click on a link in the site bar, the front color of the clicked link change to white and the rest of the link in the site bar change to drak gray (which is nearly unable to see on a black background).

I would therefore like to change the color that the links get when I click on another link.

How can I do this without activating the custom colors in the plugin ? - so that I doesn't change the other colors in the site bar or the colors of my navigation dropdown bar.

An idea to implement in the future: To make it easier for the students to see where I am on the site, It would be nice if it was possible to make the path to the viewed page lighting by using the default link color in the sitebar for the link of upper pages - when clicked on a subpage, or sub-subpage, etc.

**Comment by metinsaylan** [comment]
It totally depends on your theme. Originally this custom css should help:

div.shailan-dropdown-menu ul.dropdown li>a{ color:#f00 }
